# Generated by Django 3.0.3 on 2020-11-18 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TBApp', '0002_auto_20201117_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='email',
            field=models.EmailField(default='firstName', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='password',
            field=models.CharField(default='password', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='username',
            field=models.CharField(default='username', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
