# Generated by Django 3.0.3 on 2020-11-05 19:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TBApp', '0003_auto_20201105_1405'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Account',
            new_name='AccountInfo',
        ),
    ]
