# Generated by Django 3.0.3 on 2020-11-18 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TBApp', '0004_auto_20201117_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='email',
        ),
        migrations.RemoveField(
            model_name='account',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='password',
        ),
        migrations.RemoveField(
            model_name='account',
            name='username',
        ),
    ]
