# Generated by Django 3.0.3 on 2020-12-12 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TBApp', '0006_auto_20201117_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
