# Generated by Django 3.0.3 on 2020-12-12 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TBApp', '0007_auto_20201212_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
