# Generated by Django 3.0.3 on 2020-12-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TBApp', '0008_auto_20201212_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.CharField(max_length=50),
        ),
    ]
